### ISSUE TITLE
Unable able run the example on README page

### ISSUE THREAD

**Issue by coleslaw481** [fanzheng10/HiDeF#1]
Hi,

I am unable to run the example on the [readme page](https://github.com/fanzheng10/HiDeF#using-hidef-as-a-python-package)

Error I am seeing:

```
$ python
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> P = ['11111111',
...   '11111100',
...   '00001111',
...   '11100000',
...   '00110000',
...   '00001100',
...   '00000011']
>>> from hidef import weaver
/Users/churas/anaconda3/lib/python3.7/site-packages/pandas/compat/_optional.py:138: UserWarning: Pandas requires version '2.7.0' or newer of 'numexpr' (version '2.6.9' currently installed).
  warnings.warn(msg, UserWarning)
>>> wv = weaver.Weaver()
>>> H = wv.weave(P, cutoff=1.0)
@> initializing the graph...
@> graph initialized in 0.00s
@> removing redudant edges...
@> redundant edges removed in 0.00s
@> attaching terminal nodes to the graph...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/churas/anaconda3/lib/python3.7/site-packages/hidef/weaver.py", line 228, in weave
    self._build(**kwargs)
  File "/Users/churas/anaconda3/lib/python3.7/site-packages/hidef/weaver.py", line 401, in _build
    nodes = [node for node in G.nodes]
TypeError: 'method' object is not iterable
>>> 
```

How I created my python 3.7 environment.  I'm on a mac with 11.6

```
conda create -n hidef python=3.7
conda activate hidef
pip install hidef
```

**Comment by coleslaw481** [comment]
Found the issue, ddot had installed networkx version `1.11` and hidef does not work with the older version of networkx

**Comment by coleslaw481** [comment]
It would probably be good to set a minimum version of networkx allowed for hidef and note that in the documentation.

**Comment by fanzheng10** [comment]
hmm in requirements.txt I set networkx>2.3; somehow it didn't work?

**Comment by coleslaw481** [comment]
Oh, I don't see a `requirements.txt` file under master branch on this repo. 

![Screen Shot 2022-02-02 at 9 20 06 AM](https://user-images.githubusercontent.com/655940/152204464-76cfdb34-42fa-4289-b3dc-0af6073cf097.png)

I think you might have to specify those version requirements under `install_requires` in `setup.py` as well

**Comment by fanzheng10** [comment]
thanks, I forgot that. Could you add them and create a pull request? Thanks! 
(I don't have a handy python environment to test with so it could take me much longer)

**Comment by coleslaw481** [comment]
Sure, do you already have a requirements.txt file you can attach to this ticket? If not is networkx>=2.3 the only version requirement?

**Comment by fanzheng10** [comment]
requirements.txt is under /docs

**Comment by coleslaw481** [comment]
Pull request made https://github.com/fanzheng10/HiDeF/pull/2

I added ``a1`` to version so if its deployed to production pypi its no big deal, but this should be removed for real release.
